### PR TITLE
Upgrade conflicting gems

### PR DESCRIPTION
**Pull request by nicolastemciuc**
- Upgrade `bootsnap` from `1.4.6` to `1.18.4`
- Upgrade `cbor` from `0.5.9.6` to `0.5.9.8`
- Upgrade `jaro_winkler` from `1.5.4` to `1.5.6`
- Upgrade `puma` from `4.3.3` to `4.3.12`
- Upgrade `nokogiri` from `1.10.9` to `1.15.6`
- Upgrade `msgpack` from `1.3.3` to `1.7.2`
- Upgrade `nio4r` from `2.5.2` to `2.7.3`

### CODE REVIEW

**Comment by nicolastemciuc** [comment]
It seems that the test failed because of the Chrome version?

**Comment by nicolastemciuc** [comment]
It seems that we need to update the `node` version in the `ci.yml` in order to continue using it

**Comment by nicolastemciuc** [comment]
It seems to be related with [this](https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1641139415) comment, so I remover the `webdrivers` gem and update the `selenium-webdriver` gem as he suggested.

**Comment by santiagorodriguez96** [comment]
> It seems to be related with [this issue](https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1641139415) , so I remove the `webdrivers` gem and update the `selenium-webdriver` gem as he suggested.

We are not actually updating `selenium-web-drivers` though, right?

**Review by santiagorodriguez96 — APPROVED** [review]
Looks good to me!

**Comment by nicolastemciuc** [comment]
My bad, it seems that's at the latest version possible

**Pull request merged**
